# Generated by Django 2.1 on 2018-08-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('main_picture', models.FileField(upload_to='')),
                ('paragraph', models.CharField(max_length=500)),
                ('posted_on', models.DateTimeField()),
            ],
        ),
    ]
