# Generated by Django 2.1 on 2018-08-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('email_address', models.EmailField(max_length=255)),
                ('message', models.TextField(max_length=5000)),
            ],
        ),
    ]
