# Generated by Django 2.1 on 2018-09-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('book_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_1.BookType')),
            ],
        ),
    ]
