# Generated by Django 2.1.3 on 2018-11-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_1', '0002_book_read_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('item_total', models.IntegerField(blank=True)),
                ('book_image_url', models.CharField(max_length=10000)),
                ('book_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_1.BookType')),
            ],
        ),
    ]
